language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.2
install:
    - pip install django~=$DJANGO_VERSION
    - python setup.py develop
    - pip list
script:
    - bash test.sh
