language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
env:
  - DJANGO_VERSION=1.4.0
  - DJANGO_VERSION=1.7.0
  - DJANGO_VERSION=1.8.0
install:
  - pip install django~=$DJANGO_VERSION
  - python setup.py develop
  - pip list
script:
  - bash test.sh
matrix:
  exclude:
    - python: '3.5'
      env: DJANGO_VERSION=1.7.0
    - python: '3.3'
      env: DJANGO_VERSION=1.4.0
    - python: '3.4'
      env: DJANGO_VERSION=1.4.0
    - python: '3.5'
      env: DJANGO_VERSION=1.4.0
